blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/midwayjs/midway/discussions
    about: Ask questions and discuss with other midway community members（提出问题并与其他 midway 社区成员讨论）
